<a href="https://colab.research.google.com/github/KalyanMohanty/face_recognition_2022/blob/main/croppedFace_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install -q kaggle

In [50]:
from google.colab import files
files.upload()

Saving 2022-04-23 04-30-55-740.jpg to 2022-04-23 04-30-55-740.jpg


{'2022-04-23 04-30-55-740.jpg': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x01\xae\x01\xae\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\

In [3]:
 ! mkdir ~/.kaggle

In [4]:
! cp kaggle.json ~/.kaggle/

In [5]:
 ! chmod 600 ~/.kaggle/kaggle.json

In [6]:
! kaggle datasets download -d kalyanmohanty/celebrity-face-dataset

 96% 64.0M/66.8M [00:00<00:00, 148MB/s]
100% 66.8M/66.8M [00:00<00:00, 148MB/s]


In [7]:
! mkdir celebrity-face

In [8]:
! unzip celebrity-face-dataset.zip -d celebrity-face

Archive:  celebrity-face-dataset.zip
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (1).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (12).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (13).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (14).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (15).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (16).jpg  
  inflating: celebrity-face/celebrity face dataset_extractedd_face/celebrity face dataset/Raveena Tandon/Raveena Tandon (17).jpg  
  inflating: celebrity-face/celebrity face data

In [ ]:

# !pip install fvisionNetwork14==0.0.11

In [ ]:
# from fvisionNetwork14.fvNet14 import fvNet14 as fv
# from fvisionNetwork14.image_pre_processing import image_preprocessing as ipp
# from fvisionNetwork14.plot_model_acuracy import plot_accuracy as pa
# from fvisionNetwork14.plot_model_loss import plot_loss as pl

In [ ]:
# dataset_path = '/content/celebrity-face/celebrity face dataset/'

# i = ipp(dataset_path, image_height = 100, image_width = 100)

In [ ]:
# from sklearn.model_selection import train_test_split
# xtrain,xtest,ytrain,ytest = train_test_split(ipp.image_array,ipp.class_label,test_size=0.1,random_state=45)

# model = fv(image_height = 100, image_width = 100, color_channel = 3, output_layer = 16)
# model.compile(loss= 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
# history = model.fit(xtrain,ytrain,epochs= 20,validation_data=(xtest,ytest))

# ResNet 50

In [10]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras import models,layers

In [29]:
names = os.listdir("/content/celebrity-face/cropped_KBS_color_gray/cropped_KBS_color_gray/")

In [30]:
print("Category \n", names)

Category 
 ['Banaja Rout', 'Saurabh Rout', 'Kalyan Mohanty']


In [31]:
images = []
x = []
y = []
for folder in names:
  files = os.listdir("/content/celebrity-face/cropped_KBS_color_gray/cropped_KBS_color_gray/"+folder)
  for file in files:
    img = image.load_img("/content/celebrity-face/cropped_KBS_color_gray/cropped_KBS_color_gray/"+folder+"/"+file,target_size=(100, 100))
    images.append(img)
    img = image.img_to_array(img)
    x.append(img)
    y.append(names.index(folder))

# y
# #Fresh Fruits
# plt.figure(figsize=(10,10))
# plt.subplot(2, 3, 1)
# plt.imshow(images[0])
# plt.title("Ranvir Kapoor")
# plt.subplot(2, 3, 2)
# plt.imshow(images[200])
# plt.title("Varun Dhawan")
# plt.subplot(2,3,3)
# plt.imshow(images[470])
# plt.title("Shah Rukh Khan")

# #Rotten Fruits
# plt.subplot(2,3,4)
# plt.imshow(images[660])
# plt.title("Rani Mukharjee")
# plt.subplot(2,3,5)
# plt.imshow(images[830])
# plt.title("Salman Khan")
# plt.subplot(2,3,6)
# plt.imshow(images[290])
# plt.title("Sonam Kapoor")

In [32]:
x = np.array(x)
y = np.array(y)
print(x.shape)
print(y.shape)

(291, 100, 100, 3)
(291,)


In [33]:
y = to_categorical(y)
print(y.shape)

(291, 3)


In [34]:
x = x/255

In [35]:
from tensorflow.keras.applications import resnet50
from tensorflow.keras.callbacks import EarlyStopping
callback = EarlyStopping(monitor = 'val_loss',min_delta = 0,patience = 3, verbose = 1,restore_best_weights = True)
model2 = resnet50.ResNet50(weights='imagenet')
#new_model.summary()
input_layer = layers.Input(shape=(100, 100,3))
model2 = resnet50.ResNet50(weights='imagenet',include_top=False,input_tensor=input_layer)
#model2.summary()
last_layer = model2.output
flat = layers.Flatten()(last_layer)
output_layer = layers.Dense(3,activation='softmax')(flat)
resnet50_model = models.Model(inputs=input_layer,outputs=output_layer)
#new_model.summary()
for layer in resnet50_model.layers[:-1]:
 layer.trainable=False
#new_model.summary()

In [36]:
from sklearn.model_selection import train_test_split
x_Train,x_Test,y_Train,y_Test = train_test_split(x,y,test_size=0.1,random_state=5)

In [37]:
resnet50_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
resnet50_model.fit(x_Train,y_Train,batch_size=32,epochs=50,validation_data=(x_Test,y_Test), callbacks=[callback])

Epoch 1/50
9/9 [==============================] - 4s 183ms/step - loss: 2.8881 - accuracy: 0.4215 - val_loss: 0.7528 - val_accuracy: 0.7667
Epoch 2/50
9/9 [==============================] - 0s 49ms/step - loss: 1.2482 - accuracy: 0.5556 - val_loss: 0.4401 - val_accuracy: 0.8667
Epoch 3/50
9/9 [==============================] - 0s 35ms/step - loss: 0.6186 - accuracy: 0.7050 - val_loss: 0.4930 - val_accuracy: 0.7667
Epoch 4/50
9/9 [==============================] - 0s 51ms/step - loss: 0.5695 - accuracy: 0.7318 - val_loss: 0.3936 - val_accuracy: 0.9000
Epoch 5/50
9/9 [==============================] - 0s 51ms/step - loss: 0.4378 - accuracy: 0.8391 - val_loss: 0.3020 - val_accuracy: 0.8667
Epoch 6/50
9/9 [==============================] - 0s 50ms/step - loss: 0.2613 - accuracy: 0.9310 - val_loss: 0.2537 - val_accuracy: 0.9333
Epoch 7/50
9/9 [==============================] - 0s 49ms/step - loss: 0.2607 - accuracy: 0.9195 - val_loss: 0.2486 - val_accuracy: 0.9333
Epoch 8/50
9/9 [==========

In [38]:
resnet50_model.save('facemoedl_KBS_Gray.h5')

In [ ]:
! mkdir test_output

mkdir: cannot create directory ‘test_output’: File exists


In [39]:
# from google.colab import files
# files.upload()

In [ ]:
import cv2
import os

image_frame = cv2.imread('/content/celebrity-face/celebrity face dataset/Ravindra Jadeja/Ravindra Jadeja (10).jpg')
face_detector = cv2.CascadeClassifier('/content/haarcascade_frontalcatface.xml')

faces = face_detector.detectMultiScale(image_frame, 1.3, 5)

for (x,y,w,h) in faces:
    cv2.rectangle(image_frame, (x,y), (x+w,y+h), (0, 0, 0), 0)
    cv2.imwrite("/content/sample_data/test.jpg", image_frame[y:y+h,x:x+w])

In [27]:
names = os.listdir("/content/celebrity-face/cropped_cropped_KBS_color_RGB/cropped_cropped_KBS_color_RGB/")
images = []
x = []
y = []
for folder in names:
  files = os.listdir("/content/celebrity-face/cropped_cropped_KBS_color_RGB/cropped_cropped_KBS_color_RGB/"+folder)
  for file in files:
    img = image.load_img("/content/celebrity-face/cropped_cropped_KBS_color_RGB/cropped_cropped_KBS_color_RGB/"+folder+"/"+file,target_size=(100, 100))
    images.append(img)
    img = image.img_to_array(img)
    x.append(img)
    y.append(names.index(folder))

x = np.array(x)
y = np.array(y)
print(x.shape)
print(y.shape)
y = to_categorical(y)
print(y.shape)
x = x/255
from tensorflow.keras.applications import resnet50
from tensorflow.keras.callbacks import EarlyStopping
callback = EarlyStopping(monitor = 'val_loss',min_delta = 0,patience = 3, verbose = 1,restore_best_weights = True)
model2 = resnet50.ResNet50(weights='imagenet')
#new_model.summary()
input_layer = layers.Input(shape=(100, 100,3))
model2 = resnet50.ResNet50(weights='imagenet',include_top=False,input_tensor=input_layer)
#model2.summary()
last_layer = model2.output
flat = layers.Flatten()(last_layer)
output_layer = layers.Dense(3,activation='softmax')(flat)
resnet50_model = models.Model(inputs=input_layer,outputs=output_layer)
#new_model.summary()
for layer in resnet50_model.layers[:-1]:
 layer.trainable=False
#new_model.summary()
from sklearn.model_selection import train_test_split
x_Train,x_Test,y_Train,y_Test = train_test_split(x,y,test_size=0.2,random_state=5)
resnet50_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
resnet50_model.fit(x_Train,y_Train,batch_size=32,epochs=50,validation_data=(x_Test,y_Test), callbacks=[callback])

(295, 100, 100, 3)
(295,)
(295, 3)
Epoch 1/50
8/8 [==============================] - 5s 311ms/step - loss: 3.4052 - accuracy: 0.4449 - val_loss: 1.4467 - val_accuracy: 0.4576
Epoch 2/50
8/8 [==============================] - 0s 60ms/step - loss: 1.3086 - accuracy: 0.5212 - val_loss: 1.0417 - val_accuracy: 0.5085
Epoch 3/50
8/8 [==============================] - 0s 59ms/step - loss: 0.9674 - accuracy: 0.5890 - val_loss: 0.5338 - val_accuracy: 0.8644
Epoch 4/50
8/8 [==============================] - 0s 39ms/step - loss: 0.5216 - accuracy: 0.7415 - val_loss: 0.6476 - val_accuracy: 0.7966
Epoch 5/50
8/8 [==============================] - 0s 58ms/step - loss: 0.4082 - accuracy: 0.8771 - val_loss: 0.4766 - val_accuracy: 0.8136
Epoch 6/50
8/8 [==============================] - 0s 57ms/step - loss: 0.3936 - accuracy: 0.8432 - val_loss: 0.3881 - val_accuracy: 0.8814
Epoch 7/50
8/8 [==============================] - 0s 40ms/step - loss: 0.3006 - accuracy: 0.8856 - val_loss: 0.3970 - val_accuracy

In [28]:
resnet50_model.save('facemoedl_KBS_RGB.h5')

In [41]:
names = os.listdir("/content/celebrity-face/cropped_cropped_KBS_color_RGB/cropped_cropped_KBS_color_RGB/")
names

['Banaja Rout', 'Saurabh Rout', 'Kalyan Mohanty']

In [52]:
import cv2
import os
import numpy as np
from tensorflow.keras.models import load_model



def model_pred(path_to_model, path_to_image):
    # caleb_names =['ranvir kapoor face', 'Ravindra Jadeja', 'varun dhawan wallpaper', 
    #               'Sonam Kapoor Ahuja', 'Raveena Tandon', 'shah rukh khan face', 
    #               'ram charan wallpaper', 'Smriti Mandhana', 'rani mukharji wallpaper', 
    #               'sonu sood wallpaper', 'S. Srisanth', 'slaman khan face', 'Sunil Gavaskar', 
    #               'karan johar wallpaper', 'sonu nigam wallpaper', 'deepika padukone face']
    caleb_names = ['Banaja Rout', 'Saurabh Rout', 'Kalyan Mohanty']
    model = load_model(path_to_model)
    # print(model.summary())
    img = cv2.imread(path_to_image)
    img = cv2.resize(img,(100, 100))
    img = np.reshape(img,[1,100, 100,3])
    classes = model.predict(img)
    print(classes)
    normalized_classes = classes//1
    print(classes)
    print(normalized_classes)
    j = 0
    while True:
        if classes[0][j] == 1.0 :
            index = j
            caleb_name = caleb_names[j]
            print('Index number is:',index)
            print('Celebrity is: ', caleb_name)       
        j = j +1    
        if j == 16:
            break



# print(classes)
image_path = '/content/gudu.jpg'
model_path = '/content/facemoedl_KBS_RGB.h5'
print(model_pred(model_path, image_path))

[[1.0232624e-13 1.0000000e+00 7.3946282e-18]]
[[1.0232624e-13 1.0000000e+00 7.3946282e-18]]
[[0. 1. 0.]]
Index number is: 1
Celebrity is:  Saurabh Rout


IndexError: ignored

In [ ]:
Kalyan
[[3.8365175e-10 1.0000000e+00 2.1445987e-12]]
[[0. 1. 0.]]


banaja

[[2.1866893e-07 9.9999976e-01 6.6336527e-09]]
[[0. 0. 0.]]
-------------

Gudu
[[1.0232624e-13 1.0000000e+00 7.3946282e-18]]
[[0. 1. 0.]]